### ISSUE TITLE
delete note trigger a bug

### ISSUE THREAD

**Issue by lishoulong** [survivejs-demos/redux-demo#12]
In the immutable_app part, I follow the way to run, clone,cd,npm install,(I skip the "phantomjs-prebuilt": "^2.1.7",because of the Error.), then I run the "npm run start" instruction to run.
At first,all is ok,but when I click the node delete button,the page alert Error,just as follows:

TypeError: note is undefined
render/<
E:/kanban/redux-demo-master1/immutable_app/app/components/Notes.jsx
mapFactory/mappedSequence.__iterateUncached/<
http://localhost:8080/app.js:1993
List.prototype.__iterate
http://localhost:8080/app.js:1993
mapFactory/mappedSequence.__iterateUncached
http://localhost:8080/app.js:1993
seqIterate
http://localhost:8080/app.js:1993
IndexedSeq.prototype.__iterate
http://localhost:8080/app.js:1993
.toArray
http://localhost:8080/app.js:1993

I compare the immutable_app part with the  kanban_app,except for the immutablejs part,every thing is the same.I have no idea how to figure it.

Thanks for your help!

**Comment by bebraw** [comment]
Hi,

I couldn't reproduce the issue, but I have a rough idea of what might have caused it. If you ran the other demo first, it stashed data to the location at `localStorage` where this demo consumes it too. It's easy to end up with a weird state this way.

I changed the location for the immutable demo. I also bumped the dependencies so that they are up to date. Could you give it another go now?

**Comment by lishoulong** [comment]
Thanks for your immidiate reply,just I try to run "webpack -w" to run on the local,and run expectly on the chrome and the firefox,bug it remain the same.when I click the delete node button, the console alert error.

This in this line " <Note className="note" id={note.get('id')} key={note.get('id')}".
The chrome alert " Uncaught TypeError: Cannot read property 'get' of undefined". In this way,I guess the immutable property "get" is not being recognified. But in the other page,the get is not receive the alert.

The firefox alert in the same line that "TypeError: note is undefined".

**Comment by bebraw** [comment]
Are you sure there isn't anything weird at `localStorage`? You can try erasing its state like this through console:

``` javascript
localStorage.clear();
localStorage.debug = 1;
```

To enable persistency again, set

``` javascript
localStorage.debug = 0;
```

`debug` is a little escape hatch I made for situations like this. It just tells the app not to touch `localStorage` if it's set.

Can you try this and report back? You can also try adding `console.log(notes)` at `Notes.jsx` to understand the state a little better. Redux dev tools (visible by default) likely give some insight as well. 

The problem is that I cannot reproduce the issue so it's very hard for me to fix.

**Comment by lishoulong** [comment]
OK,I try it ,then give your reply.
             thanks!

**Comment by lishoulong** [comment]
Just now,as your instructions,I clear the localStorage,and set localStorage.debug = 0;I am using the redux dev tools, re-run the project,when I click "delete the note", in the redux dev tools the notes decrease accordingly. But in the view ,the note is just there,it is not disappear.And in the console the same Error follows.(sorry I can not upload the printscreen because of the net restriction.)

console.log(notes),I can just add into the render`s return  of nodes.jsx,but I cannot find the content in the console.I think the notes state in the redux dev tools can replace it.

**Comment by bebraw** [comment]
Ok. Let's leave this open for now. Perhaps someone else can reproduce the issue so we get more debug information. 👍

**Comment by lishoulong** [comment]
OK,thanks Bebraw for your reply ,it is my pleasure to communicate with you.

**Comment by bebraw** [comment]
@lishoulong It's alright. I noticed one more thing. The code triggered `update note` after deletion. I added some code to prevent this. I'm not sure if it fixes this issue, but it was a good check to add. 😄

**Comment by lishoulong** [comment]
Yes,that`s it, the "delete note" operation trigger two actions,"DELETE_NOTE" and "UPDATE_NOTE".

**Comment by bebraw** [comment]
@lishoulong Did you try with my fix?

**Comment by lishoulong** [comment]
Hi,I just try your fix. First let`s check your fix.
"
onDelete={(id, e) => this.deleteNote(laneId, id, e)} />

deleteNote(laneId, noteId, e) {
    e.stopPropagation();

```
this.props.detachFromLane(laneId, noteId);
this.props.deleteNote(noteId);
```

  }
"
after running,I also get the same error "Uncaught TypeError: Cannot read property 'get' of undefined".

**Comment by bebraw** [comment]
Ok, it's something else then. Better wait for more info. Thanks. 👍

**Comment by lishoulong** [comment]
OK.

**Comment by bebraw** [comment]
Time to close. Please re-open if you can repro!
